POST localhost:8080/studentCourseMark/create
Content-Type: application/json

{
  "student": "beka",
  "courseName": "data base",
  "mark": "5"

}

### get student list
GET localhost:8080/studentCourseMark/get/all